#!/bin/bash
# LAMINAR MIRROR: BRAID SDK POLYGLOT INIT
export BRAID_CORE="$HOME/.vesper/src/santos_tse"
export BRAID_LANE_COUNT=7
export BRAID_PARITY_SCALAR=0.6180339887
echo "[|||] BRAID POLYGLOT ENVIRONMENT: SECURED & LOADED."
