#!/usr/bin/env python3
# VESPER-01 // KERNEL FUSION BRIDGE
# PURPOSE: Inject Live Observatory Telemetry into Santos_X_Compiler

import json
import os

# Path to the observatory state file
STATE_PATH = "/tmp/observatory_state.json"
HEADER_PATH = os.path.expanduser("~/.vesper/include/kernel_live_data.h")

def fuse():
    if not os.path.exists(STATE_PATH):
        print("[!] OBSERVATORY DATA NOT FOUND. ABORTING FUSION.")
        return

    with open(STATE_PATH, "r") as f:
        data = json.load(f)

    # Generate C-Header
    with open(HEADER_PATH, "w") as h:
        h.write("// AUTO-GENERATED BY VSPR_KERNEL_FUSE\n")
        h.write(f"#define LIVE_WEIGHT_SHA \"{data.get('weights_sha', 'NULL')}\"\n")
        h.write(f"#define LIVE_PHYSICS_DOMAIN \"{data.get('science_title', 'NULL')}\"\n")
        h.write("// END OF FUSION HEADER\n")

    print(f"[|||] FUSION SUCCESS: {HEADER_PATH} UPDATED.")

if __name__ == "__main__":
    fuse()
